my_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('p_library.urls')),
    path('accounts/', include('allauth.urls')),
    #path('accounts/profile', include('p_library.urls'))
    #re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    #re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

p_library/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import login, logout

from p_library import views

app_name = 'p_library'


urlpatterns = [
    path('', views.BookList.as_view(), name="book_list"),
    path('update/profile', views.edit_profile, name='user_edit'),
    #path('login/', login, name='login'),
    #path('logout/', views.MyLogoutView.as_view(), name='logout'),

    path('login/', login, name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),

    path('create', views.BookCreate.as_view(), name="book_create"),
    path("update<int:pk>", views.BookUpdate.as_view(), name="book_update"),
    path('index/', views.index, name='library'),
    path('library/', views.index, name='library'),
    path('library/book_increment/', views.book_increment),
    path('library/book_decrement/', views.book_decrement),
    path('library/borrowed_book/', views.borrowed_book),
    path('library/returned_book/', views.returned_book),
    path('authors/', views.AuthorList.as_view(), name='author_list'),
    path('authors/create', views.AuthorCreate.as_view(), name='author_create'),
    path("authors/update<int:pk>", views.AuthorUpdate.as_view(), name="author_update"),
    path('publishers/', views.PublisherList.as_view(), name='publisher_list'),
    path('publishers/create', views.PublisherCreate.as_view(), name='publisher_create'),
    path("publishers/update<int:pk>", views.PublisherUpdate.as_view(), name="publisher_update"),
    path('friends/', views.FriendList.as_view(), name='friend_list'),
    path('friends/create', views.FriendCreate.as_view(), name='friend_create'),
    path("friends/update<int:pk>", views.FriendUpdate.as_view(), name="friend_update"),
]

p_library/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    full_name = models.TextField()
    birth_year = models.SmallIntegerField()
    country = models.CharField(max_length=2)

    def __str__(self):
        return self.full_name


class Publisher(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name


class Friend(models.Model):
    full_name = models.TextField()
    def __str__(self):
        return self.full_name


class Book(models.Model):
    ISBN = models.CharField(max_length=13)
    title = models.TextField()
    description = models.TextField()
    year_release = models.SmallIntegerField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    copy_count = models.CharField(max_length=100, default=1)
    price = models.DecimalField(decimal_places=2, max_digits=10000, default=0.00)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, blank=True, null=True,)
    friend = models.ManyToManyField(Friend, blank=True, related_name='friends')
    borrowed_book_count = models.SmallIntegerField(default=0)
    cover = models.ImageField(verbose_name='Обложка', upload_to='covers', blank=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, verbose_name=u'Пользователь', on_delete=models.CASCADE, related_name='profile' )
    country = models.CharField(
        verbose_name=u'Страна',
        max_length=50,
        blank=True
        )
    location = models.CharField(
        verbose_name=u'Город',
        max_length=30,
        blank=True
        )
    birth_date = models.DateField(
        verbose_name=u'Дата рождения',
        null=True,
        blank=True
        )

    class Meta:
        verbose_name = 'Данные пользователя'
        verbose_name_plural = 'Данные пользователей'

    def __str__(self):
        return self.user.username

p_library/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.template import loader
from p_library.models import Author, Book, Publisher, Friend, UserProfile
from p_library.forms import AuthorForm, BookForm, PublisherForm, FriendForm, UserRegistrationForm, UserForm, UserProfileForm
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.forms import formset_factory
from django.http.response import HttpResponseRedirect
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from allauth.account.views import LogoutView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from allauth.socialaccount.models import SocialAccount


class MyLogoutView(LogoutView):
    template_name = 'logout.html'


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, instance=request.user.profile)
        print(profile_form)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('/')
    else:
        user_form = UserForm(instance=request.user)
        try:
            profile_form = UserProfileForm(instance=request.user.profile)
        except:
            profile_form = UserProfileForm(instance=UserProfile.objects.create(user=request.user))
        print(profile_form)
    return render(request, 'user_edit.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


class AuthorUpdate(UpdateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_edit.html'


class AuthorCreate(CreateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_edit.html'


class AuthorList(ListView):
    model = Author
    template_name = 'author_list.html'


class BookUpdate(UpdateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('p_library:book_list')
    template_name = 'book_edit.html'


class BookCreate(CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('p_library:book_list')
    template_name = 'book_edit.html'


class BookList(ListView):
    model = Book
    template_name = 'book_list.html'


class PublisherUpdate(UpdateView):
    model = Publisher
    form_class = PublisherForm
    success_url = reverse_lazy('p_library:publisher_list')
    template_name = 'publisher_edit.html'


class PublisherCreate(CreateView):
    model = Publisher
    form_class = PublisherForm
    success_url = reverse_lazy('p_library:publisher_list')
    template_name = 'publisher_edit.html'


class PublisherList(ListView):
    model = Publisher
    template_name = 'publisher_list.html'


class FriendUpdate(UpdateView):
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'friend_edit.html'


class FriendCreate(CreateView):
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'friend_edit.html'


class FriendList(ListView):
    model = Friend
    template_name = 'friend_list.html'


def log_in(request, template, context):
    if request.method == 'POST':
        if 'btnSignIn' in request.POST:
            user_form = UserRegistrationForm(request.POST)
            if user_form.is_valid():
                new_user = user_form.save(commit=False)
                new_user.set_password(user_form.cleaned_data['password'])
                new_user.save()
                login(request, authenticate(username=user_form.cleaned_data['username'], password=user_form.cleaned_data['password']))
            else:
                context['errmsg'] = "Введите логин и пароль ещё раз!"
        else:
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                auth.login(request, form.get_user())
            else:
                context['errmsg'] = "Неверный логин или пароль!"
    else:
        context['form'] = AuthenticationForm()
    return HttpResponse(template.render(context, request))


def get_extra_data(request):
    try:
        github_url = SocialAccount.objects.get(provider='github', user=request.user).extra_data['html_url']
    except:
        github_url = None
    print(github_url)
    return github_url


def index(request):
    template = loader.get_template('library.html')
    books = Book.objects.all()
    friends = Friend.objects.all()
    github_url = get_extra_data(request)
    context = {
        "title": "мою библиотеку",
        "books": books,
        "friends": friends,
        "github_url": github_url,
    }
    return HttpResponse(template.render(context, request))


def book_list(request):
    template = loader.get_template('book_list.html')
    books = Book.objects.all()
    github_url = get_extra_data(request)
    context = {
        "books": books,
        "github_url": github_url,
    }
    if request.user.is_authenticated:
        return HttpResponse(template.render(context, request))
    return log_in(request, template, context)

def author_list(request):
    template = loader.get_template('author_list.html')
    authors = Author.objects.all()
    github_url = get_extra_data(request)
    context = {
        "authors": authors,
        "github_url": github_url,
    }
    if request.user.is_authenticated:
        return HttpResponse(template.render(context, request))
    return log_in(request, template, context)

def publisher_list(request):
    template = loader.get_template('publisher_list.html')
    publishers = Publisher.objects.all()
    github_url = get_extra_data(request)
    context = {
        "publishers": publishers,
        "github_url": github_url,
    }
    if request.user.is_authenticated:
        return HttpResponse(template.render(context, request))
    return log_in(request, template, context)

def friend_list(request):
    template = loader.get_template('friend_list.html')
    friends = Friend.objects.all()
    github_url = get_extra_data(request)
    context = {
        "friends": friends,
        "github_url": github_url,
    }
    if request.user.is_authenticated:
        return HttpResponse(template.render(context, request))
    return log_in(request, template, context)

def library(request):
    template = loader.get_template('library.html')
    books = Book.objects.all()
    friends = Friend.objects.all()
    github_url = get_extra_data(request)
    context = {
        "title": "мою библиотеку",
        "books": books,
        "friends": friends,
        "github_url": github_url,
    }
    if request.user.is_authenticated:
        return HttpResponse(template.render(context, request))
    return log_in(request, template, context)

def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/library/')
            book.copy_count = int(book.copy_count) + 1
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/library/')
            if int(book.copy_count) < 1:
                book.copy_count = 0
            else:
                book.copy_count = int(book.copy_count) - 1
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

def borrowed_book(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        friend_id = request.POST['select_borrowed']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            friend = Friend.objects.get(id=friend_id)
            if not book:
                return redirect('/library/')
            if int(book.copy_count) < 1:
                book.copy_count = 0
            else:
                book.copy_count = int(book.copy_count) - 1
                book.borrowed_book_count = int(book.copy_count) + 1
                book.friend.add(friend)
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

def returned_book(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        friend_id = request.POST['select_returned']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            friend = Friend.objects.get(id=friend_id)
            if not book:
                return redirect('/library/')
            if int(book.borrowed_book_count) < 1:
                book.borrowed_book_count = 0
            else:
                book.copy_count = int(book.borrowed_book_count) + 1
                book.borrowed_book_count = int(book.borrowed_book_count) - 1
                book.friend.remove(friend)
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

p_library/templates/author_edit.html
{% extends 'index.html' %}

{% block title %}Форма создания и редактирования авторов{% endblock %}

{% block title_h2 %}Форма создания и редактирования авторов:{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Сохранить">
</form>
{% endblock %}

p_library/templates/author_list.html
{% extends 'index.html' %}

{% block title %}Моя библиотека{% endblock %}

{% block link %}

    <div class="d-flex justify-content-between align-items-center bg-light">
        <div class="mx-2 my-2 h5 font-weight-bold">Привет,
            {% if github_url %}
            <a class="text-primary" href="{{ github_url }}">{{ user }}</a>!
            {% elif user.is_superuser %}
            <a class="text-primary" href="/admin/">{{ user }}</a>!
            {% else %}
            <span class="text-primary">{{ user }}</span>!
            {% endif %}
            <a class="text-secondary" href="{%url 'p_library:user_edit'%}"><img src="/media/icon/settings.ico" alt=""></a>
        </div>
        <a class="btn btn-outline-primary mx-2 my-2" href="{%url 'p_library:logout'%}">Выход</a>
    </div>
                <div class="text-secondary text-center font-weight-bold my-3">
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:library'%}">Библиотека</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:book_list'%}">Книги</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:publisher_list'%}">Издательства</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:friend_list'%}">Друзья</a>
                </div>
{% endblock %}

{% block title_h2 %}Список авторов книг:{% endblock %}

{% block content %}
<table class="table table-stripped table-hover">
                    {% for author in object_list %}
                    <tr class="table-bordered">
                        <td style="width:20px;">{{ forloop.counter }}</td>
                        <td>{{ author.full_name }}</td>
                        <td style="width:20px;text-align:right;"><a class="btn btn-outline-primary" href="{%url 'p_library:author_update' author.id %}">Изменить</a></td>
                    </tr>
                    {% endfor %}
                </table>
                <a class="btn btn-success my-3" href="{%url 'p_library:author_create'%}">Добавить автора</a>
{% endblock %}

p_library/templates/book_edit.html
{% extends 'index.html' %}

{% block title %}Форма создания и редактирования книг{% endblock %}

{% block title_h2 %}Форма создания и редактирования книг:{% endblock %}

{% block content %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-success my-3" type="submit" value="Сохранить">
                <a class="btn btn-danger my-3" href="{%url 'p_library:book_list'%}">Отмена</a>
            </form>
{% endblock %}

p_library/templates/book_list.html
{% extends 'index.html' %}
{% block title %}Моя библиотека{% endblock %}
{% block link %}
    <div class="d-flex justify-content-between align-items-center bg-light">
        <div class="mx-2 my-2 h5 font-weight-bold">Привет,
            {% if github_url %}
            <a class="text-primary" href="{{ github_url }}">{{ user }}</a>!
            {% elif user.is_superuser %}
            <a class="text-primary" href="/admin/">{{ user }}</a>!
            {% else %}
            <span class="text-primary">{{ user }}</span>!
            {% endif %}
            <a class="text-secondary" href="{%url 'p_library:user_edit'%}"><img src="/media/icon/settings.ico" alt=""></a>
        </div>
        <a class="btn btn-outline-primary mx-2 my-2" href="{%url 'p_library:logout'%}">Выход</a>
    </div>
            	<div class="text-secondary text-center font-weight-bold my-3">
	            	<a class="text-secondary text-decoration-none" href="{%url 'p_library:library'%}">Библиотека</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:author_list'%}">Авторы</a> |
	            	<a class="text-secondary text-decoration-none" href="{%url 'p_library:publisher_list'%}">Издательства</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:friend_list'%}">Друзья</a>
            	</div>
    <div class="container my-4">
        <a class="btn btn-success" href="{%url 'p_library:book_create'%}">Добавить книгу в библиотеку</a>
    </div>

{% endblock %}

{% block title_h2 %}Список книг:{% endblock %}

{% block content %}
                <ul class="container list-group list-group-flush">
            {% for book in object_list %}
            <div class="row mt-3">
                <div class="col">
                    <ul class="list-group text-secondary">
                        <h1 class="h3 font-weight-bold mt-5">{{book.title}}</h1>
                        <li class="d-flex justify-content-between list-group-item">
                            <div class="h5 font-italic">{{book.author}}</div>
                            <div class="h5 font-bold">{{book.year_release}}</div>
                        </li>
                        <li class="d-flex list-group-item">
                            <p class="h5 font-weight-light">{{book.description|truncatechars:200}}</p>
                        </li>
                        <div class="col text-right mx-5 my-3">
                            <a class="btn btn-outline-primary" href="{%url 'p_library:book_update' book.id %}">Изменить</a>
                        </div>

                    </ul>
                </div>
                {%if book.cover%}
                <div class="col text-right">
                    <img src="{{ book.cover.url }}" alt="" width="200">
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </ul>
    <div class="container my-3">
        <a class="btn btn-success" href="{%url 'p_library:book_create'%}">Добавить книгу в библиотеку</a>
    </div>

{% endblock %}

p_library/templates/friend_edit.html
{% extends 'index.html' %}
{% block title %}Форма создания и редактирования друзей{% endblock %}
{% block title_h2 %}Форма создания и редактирования друзей:{% endblock %}
{% block content %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-success my-3" type="submit" value="Сохранить">
                <a class="btn btn-danger my-3" href="{%url 'p_library:friend_list'%}">Отмена</a>
            </form>
{% endblock %}

p_library/templates/friend_list.html
{% extends 'index.html' %}
{% block title %}Моя библиотека{% endblock %}
{% block link %}

    <div class="d-flex justify-content-between align-items-center bg-light">
        <div class="mx-2 my-2 h5 font-weight-bold">Привет,
            {% if github_url %}
            <a class="text-primary" href="{{ github_url }}">{{ user }}</a>!
            {% elif user.is_superuser %}
            <a class="text-primary" href="/admin/">{{ user }}</a>!
            {% else %}
            <span class="text-primary">{{ user }}</span>!
            {% endif %}
            <a class="text-secondary" href="{%url 'p_library:user_edit'%}"><img src="/media/icon/settings.ico" alt=""></a>
        </div>
        <a class="btn btn-outline-primary mx-2 my-2" href="{%url 'p_library:logout'%}">Выход</a>
    </div>
                <div class="text-secondary text-center font-weight-bold my-5">
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:library'%}">Библиотека</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:book_list'%}">Книги</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:author_list'%}">Авторы</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:publisher_list'%}">Издательства</a>
                </div>
{% endblock %}

{% block title_h2 %}Список друзей:{% endblock %}

{% block content %}

                <table class="table table-stripped table-hover">
                    {% for friend in object_list %}
                    <tr class="table-bordered">
                        <td style="width:20px;">{{ forloop.counter }}</td>
                        <td>{{ friend.full_name }}</td>
                        <td style="width:20px;text-align:right;">
                            <a class="btn btn-outline-primary" href="{%url 'p_library:friend_update' friend.id %}">Изменить</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
                <a class="btn btn-success my-3" href="{%url 'p_library:friend_create'%}">Добавить друга</a>
{% endblock %}

p_library/templates/library.html
{% extends 'index.html' %}
{% block title %}Моя библиотека{% endblock %}
{% block link %}
    <div class="d-flex justify-content-between align-items-center bg-light">
        <div class="mx-2 my-2 h5 font-weight-bold">Привет,
            {% if github_url %}
            <a class="text-primary" href="{{ github_url }}">{{ user }}</a>!
            {% elif user.is_superuser %}
            <a class="text-primary" href="/admin/">{{ user }}</a>!
            {% else %}
            <span class="text-primary">{{ user }}</span>!
            {% endif %}
            <a class="text-secondary" href="{%url 'p_library:user_edit'%}"><img src="/media/icon/settings.ico" alt=""></a>
        </div>
        <a class="btn btn-outline-primary mx-2 my-2" href="{%url 'p_library:logout'%}">Выход</a>
    </div>
    <div class="text-secondary text-center font-weight-bold my-3">
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:book_list'%}">Книги</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:author_list'%}">Авторы</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:publisher_list'%}">Издательства</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:friend_list'%}">Друзья</a>
    </div>

{% endblock %}

{% block content %}

    <h3 class="text-secondary text-center my-3">Добро пожаловать в {{ title }}.</h3>
    <h5 class="text-secondary text-center my-3">Тут собрано {{ books|length }} книг из моей личной коллекции.</h5>
    <table class="table table-stripped table-hover">
        <thead class="thead-light">
            <tr class="table-bordered text-center">
                <th>№</th>
                <th>Название книги</th>
                <th>Обложка</th>
                <th>ISBN</th>
                <th>О книге</th>
                <th>Год</th>
                <th>Автор</th>
                <th>Издательство</th>
                <th>Страна</th>
                <th>Кол-во книг в библиотеке</th>
                <th>Кол-во одолженных книг и кто одолжил</th>
                <th>Изменить кол-во книг в библиотеке</th>
                <th>Одолжить или вернуть книги</th>
            </tr>
        </thead>
        <tbody class="table-bordered text-center">
            {% for book in books %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ book.title }}</td>
                <td>
                    {% if book.cover %}
                    <img src="{{ book.cover.url }}" width="100" alt="">
                    {% endif %}
                </td>
                <td>{{ book.ISBN }}</td>
                <td>{{ book.description }}</td>
                <td>{{ book.year_release }}</td>
                <td>{{ book.author.full_name }}</td>
                <td>{{ book.publisher }}</td>
                <td>{{ book.author.country }}</td>
                <td>{{ book.copy_count }}</td>
                <td>
                    <p>{{ book.borrowed_book_count }}</p>
                    {% for friend in friends.all %}
                    {% if friend in book.friend.all %}
                    <p class="my-1 px-1 py-1 bg-secondary text-white rounded">{{ friend.full_name }}</p>
                    {% endif %}
                    {% endfor %}
                </td>
                <td>
                    <form class="my-2" action="/library/book_increment/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ book.id }}" />
                        <input class="btn btn-outline-info btn-sm" type="submit" value="Увеличить кол-во" />
                    </form>
                    <form class="my-2" action="/library/book_decrement/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ book.id }}" />
                        <input class="btn btn-outline-success btn-sm" type="submit" value="Уменьшить кол-во" />
                    </form>
                </td>
                <td>
                    {% if book.copy_count and book.friend.all|length != friends.all|length %}
                    <form class="form-row" action="/library/borrowed_book/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <select style="width:20vw;" class="col custom-select my-1 mr-sm-2" name="select_borrowed" size="1">
                            {% for friend in friends.all %}
                            {% if friend not in book.friend.all %}
                            <option value="{{ friend.id }}">{{ friend.full_name }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                        <input type="hidden" name="id" value="{{ book.id }}" />
                        <input class="col btn btn-outline-warning my-1" type="submit" value="Одолжить" />
                    </form>
                    {% endif %}
                    {% if book.friend.all %}
                    <form class="form-row" action="/library/returned_book/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <select style="width:20vw;" class="col custom-select my-1 mr-sm-2" name="select_returned" size="1">
                            {% for friend in book.friend.all %}
                            <option value="{{ friend.id }}">{{ friend.full_name }}</option>
                            {% endfor %}
                        </select>
                        <input type="hidden" name="id" value="{{ book.id }}" />
                        <input class="col btn btn-success my-1" type="submit" value="Вернуть" />
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        <tbody>
    </table>
 
{% endblock %}

p_library/templates/publisher_list.html
{% extends 'index.html' %}
{% block title %}Моя библиотека{% endblock %}
{% block link %}

    <div class="d-flex justify-content-between align-items-center bg-light">
        <div class="mx-2 my-2 h5 font-weight-bold">Привет,
            {% if github_url %}
            <a class="text-primary" href="{{ github_url }}">{{ user }}</a>!
            {% elif user.is_superuser %}
            <a class="text-primary" href="/admin/">{{ user }}</a>!
            {% else %}
            <span class="text-primary">{{ user }}</span>!
            {% endif %}
            <a class="text-secondary" href="{%url 'p_library:user_edit'%}"><img src="/media/icon/settings.ico" alt=""></a>
        </div>
        <a class="btn btn-outline-primary mx-2 my-2" href="{%url 'p_library:logout'%}">Выход</a>
    </div>                <div class="text-secondary text-center font-weight-bold my-3">
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:library'%}">Библиотека</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:book_list'%}">Книги</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:author_list'%}">Авторы</a> |
                    <a class="text-secondary text-decoration-none" href="{%url 'p_library:friend_list'%}">Друзья</a>
                </div>
{% endblock %}

{% block title_h2 %}Список издательств:{% endblock %}

{% block content %}
                {% for publisher in object_list %}
                    <ul class="list-group font-weight-bold">
                        <li class="list-group-item my-3">
                            {{ publisher.name }}
                            <ul class="list-group">
                                {% for book in publisher.books.all %}
                                    <li class="list-group-item list-group-item-secondary"> {{ book.title }}</li>
                                {% endfor %}
                            </ul>
                            <div style="margin-top:10px;text-align:right;">
                                <a class="btn btn-outline-primary" href="{%url 'p_library:publisher_update' publisher.id %}">Изменить</a></div>
                        </li>
                    </ul>
                {% endfor %}
                <a class="btn btn-success my-3" href="{%url 'p_library:publisher_create'%}">Добавить издательство</a>
{% endblock %}